#ifndef UBXUNDOREDOMANAGER_GLOBAL_H
#define UBXUNDOREDOMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBXUNDOREDOMANAGER_LIBRARY)
#  define UBXUNDOREDOMANAGER_API Q_DECL_EXPORT
#else
#  define UBXUNDOREDOMANAGER_API Q_DECL_IMPORT
#endif

#endif // UBXUNDOREDOMANAGER_GLOBAL_H
