/*
* Copyright (c) 2015, 深圳市优必选科技有限公司
* All rights reserved.
* 
* 文件名称：UI_TEXT_ID.h
* 创建时间：2015/09/16 14:10
* 文件标识：
* 文件摘要：界面文本定义
* 
* 当前版本：1.0.0.0
* 作    者：ZDJ
* 完成时间：2015/09/16 14:10
* 版本摘要：
*/
#pragma once

#define ID_ACTLIST_HEADER_RUNTIME      //动作列表标题“运行时间”
#define ID_ACTLIST_HEADER_ALLTIME      //动作列表标题“总时间”
#define ID_HELP_FIREWAREVERSION        //固件版本
#define ID_UPDATEACT_ACTLIST_HEADER_PREVIEW  //预览
#define ID_UPDATEACT_ACTLIST_HEADER_NAME     //名称
#define ID_UPDATEACT_ACTLIST_HEADER_DESC     //简介
#define ID_UPDATEACT_ACTLIST_HEADER_TIME     //时间
#define ID_UPDATEACT_ACTLIST_HEADER_SIZE     //大小
#define ID_UPDATEACT_ACTLIST_HEADER_OPER     //操作
#define ID_HELP_ACTUPDATE                    //动作表更新
#define ID_UPDATEACT_ACTLIST_GBOX_TEXT       //动作表列表
#define ID_UPDATEACT_ACTLIST_BTN_REFRESH_TEXT //刷新
#define ID_UPDATEACT_ACTLIST_BTN_CLOSE_TEXT   //关闭
#define ID_UPDATEACT_ACTLIST_BTN_SELECTALL_TEXT  //全选
#define ID_UPDATEACT_BTN_DOWNLOAD_TEXT        //下载
#define ID_UPDATEACT_ACTLIST_HEADER_PROGRESS   //进度
#define ID_UPDATEACT_ACTLIST_DOWNLOADING_TEXT  //下载中
#define ID_TEXT_DOWNLOADED                     //已下载
#define ID_TEXT_DOWNLOADING                    //正在下载
#define ID_TEXT_NOTEXIST                       //不存在
#define ID_TEXT_TRANSFILE_REQ                  //请求传输文件失败
#define ID_TEXT_SYNC_ING                       //正在同步
#define ID_TEXT_SYNC_FAILED                    //同步失败
#define ID_TEXT_FAILED                         //失败
#define ID_TEXT_SUCCESS                        //成功
#define ID_TEXT_TIME_REMAIN                    //剩余时间
#define ID_TEXT_DISCONNECT                     //断开连接
#define ID_TEXT_SYNC_ACTION                    //同步动作
#define ID_TEXT_FAVOUR                         //收藏
#define ID_TEXT_PARISE                         //赞
#define ID_TEXT_HOTRECOMMEND                   //热门推荐
#define ID_TEXT_LASTUPDATE                     //最新更新
#define ID_TEXT_MOSTCOMMENT                    //最多评论
#define ID_TEXT_OFFIACTION                     //官方动作
#define ID_TEXT_DOWNLOAD                       //下载
#define ID_TEXT_ALL                            //全部
#define ID_TEXT_BASICACT                       //基本动作
#define ID_TEXT_MUSICACT                       //音乐舞蹈
#define ID_TEXT_STORYACT                       //寓言故事
#define ID_TEXT_LOGIN                          //登录
#define ID_TEXT_ACTIONLIB                      //动作库
#define ID_TEXT_LOCALACT                       //本地动作
#define ID_TEXT_ADDACT                         //添加动作
#define ID_TEXT_OK                             //确定
#define ID_TEXT_SELECTACTDIR                   //请选择本地动作库文件夹
#define ID_TEXT_MAILSENDED                     //我们给您的邮箱发送了一封修改密码邮件
#define ID_TEXT_MAILSENDFAILED                 //发送密码邮件失败
#define ID_TEXT_AREACODEEMPTY                  //国家码不能为空
#define ID_TEXT_USERFMT_ERROR                  //用户名格式不对
#define ID_TEXT_MAILCANUSE                     //邮箱可用
#define ID_TEXT_PHONEORMAIL                    //手机号或邮箱
#define ID_TEXT_USEREMPTY                      //用户名不能为空
#define ID_TEXT_EMAILFORMATERROR               //邮箱格式错误
#define ID_TEXT_PWDEMPTY                       //密码为空
#define ID_TEXT_ACTDOWNLOAD                    //动作表下载
#define ID_TEXT_USERORPWDERROR                 //帐号或密码错误
#define ID_TEXT_PWDERROR                       //密码不正确
#define ID_TEXT_CODECANUSE                     //国家码可用
#define ID_TEXT_USERCANUSE                     //用户名可用
#define ID_TEXT_PWDLENERROR                    //请输入6到15位密码
#define ID_TEXT_PWDCANUSE                      //密码可用
#define ID_TEXT_MAILCANNOTUSE                  //邮箱不可用
#define ID_TEXT_PWD2ERROR                      //重复输入密码错误
#define ID_TEXT_VERIFYCODEERROR                //验证码错误
#define ID_TEXT_REGSUCCESS                     //帐号已注册成功
#define ID_TEXT_MAILNOEMPTY                    //邮箱不能为空
#define ID_TEXT_PWDFMTERROR                    //密码不可包含字母或数字之外的字符
#define ID_TEXT_PWD2OK                         //两次密码相同
#define ID_TEXT_PWD2ERROR                      //两次密码不相同
#define ID_TEXT_PHONENUMERROR                  //手机号错误
#define ID_TEXT_SMSSENDED                      //短信验证码已发送到您手机，请查收
#define ID_TEXT_SMSSENDFAILED                  //短信验证码发送失败
#define ID_TEXT_PHONENUMNOUSE                  //手机号不可用
#define ID_TEXT_PHONENUMNOEMPTY                //手机号不能为空
#define ID_TEXT_PHONENUMCANUSE                 //手机号可用
#define ID_TEXT_VERIFYCODEOK                   //验证码正确
#define ID_TEXT_INPUTNEWPWD                    //输入新密码
#define ID_TEXT_INPUTPWD2                      //再次输入密码
#define ID_TEXT_PWDMODSUCCESS                  //密码修改成功
#define ID_TEXT_PWDMODFAILED                   //密码修改失败
#define ID_TEXT_VERIFYCODE_SMS_HEAD            //我们已向您手机尾号为
#define ID_TEXT_VERIFYCODE_SMS_TAIL            //的手机发送了一条验证码，请输入并按回车
#define ID_TEXT_FINDPWD                        //找回密码
#define ID_TEXT_GETVCODE_TIMETIP               //后可再获取验证码
#define ID_TEXT_REGISTE                        //注册
#define ID_TEXT_FORGETPWD                      //忘记密码
#define ID_TEXT_PHONELOGIN                     //手机登录
#define ID_TEXT_EMAILLOGIN                     //邮箱登录
#define ID_TEXT_USERNAME                       //用户名
#define ID_TEXT_ADDSYMBOL                      //加区号
#define ID_TEXT_PASSWORD                       //密码
#define ID_TEXT_GETVERIFYCODE                  //获取验证码
#define ID_TEXT_EMAIL                          //邮箱
#define ID_TEXT_MORE                           //更多
#define ID_TEXT_COUNTRY                        //国家
#define ID_TEXT_PHONENUM                       //手机号
#define ID_TEXT_FINISH                         //完成
#define ID_TEXT_EMAILREG                       //邮箱注册
#define ID_TEXT_PHONEREG                       //手机注册
#define ID_TEXT_PERSONINFO                     //个人信息
#define ID_TEXT_LOGOUT                         //退出登录
#define ID_TEXT_PHONEEXIST                     //手机号已存在
#define ID_TEXT_EMAILEXIST                     //邮箱已存在
#define ID_TEXT_NEEDSELACT                     //请选择动作
#define ID_TEXT_OPENDIR                        //打开文件夹
#define ID_TEXT_COUNTRYEMPTY                   //国家码为空
#define ID_TEXT_PHONENOTREG                    //手机号未注册
#define ID_TEXT_MAILNOTREG                     //邮箱未注册
#define ID_TEXT_MAILERROR                      //邮箱错误
#define ID_TEXT_ACTFILECHECKERROR              //动作表检查出错
#define ID_TEXT_REQUEST_CONNECT_FAIL           //请求连接失败
#define ID_TEXT_REQUEST_NO_RESPONSES           //请求没有回应
#define ID_TEXT_UNKNOWNERROR                   //未知错误
#define ID_TEXT_TASKDOING                      //任务正在进行中
#define ID_TEXT_ASKLOGIN                       //请登录后再操作
#define ID_TEXT_GERMAN                         //德语
#define ID_TEXT_SPANISH                        //西班牙语
#define ID_TEXT_RUSSIAN                        //俄语
#define ID_TEXT_ARABIC                         //阿拉伯语
#define ID_TEXT_FRENCH                         //法语
#define ID_TEXT_MUSICLAYER_GROUPLIST           //音乐层组列表
#define ID_TEXT_MUSICLAYER_BLOCKLIST           //音乐层块列表
#define ID_TEXT_ADDLAYER                       //增加层
#define ID_TEXT_REMOVELAYER                    //移除层
#define ID_TEXT_ADD                            //添加
#define ID_TEXT_READBACK_ALL                   //全部回读
#define ID_TEXT_READBACK_HAND                  //手部回读
#define ID_TEXT_READBACK_LEG                   //腿部回读
#define ID_TEXT_RESET                          //重置
#define ID_TEXT_BLANKNUM                       //空白块数
#define ID_TEXT_STARTTIME                      //起始时间
#define ID_TEXT_ENDTIME                        //终止时间
#define ID_TEXT_DESC                           //描述信息
#define ID_TEXT_MODDESC                        //修改描述
#define ID_TEXT_BLANKBLOCK_ADD                 //添加空白块
#define ID_TEXT_SETTIME                        //设置时间
#define ID_TEXT_MODCELLINFO                    //修改单元格信息
#define ID_TEXT_BEATVALUE                      //节拍值
#define ID_TEXT_BEATVALUE_DESC                 //节拍值是一首音乐平均每分钟的拍数，时间刻度为一拍所占用的时间
#define ID_TEXT_SETNAME                        //设置名称
#define ID_TEXT_CMDBLOCKNAME                   //指令块名称
#define ID_TEXT_MOD                            //修改
#define ID_TEXT_DELETE                         //删除
#define ID_TEXT_INSERT                         //插入
#define ID_TEXT_SPLIT                          //拆分
#define ID_TEXT_INSERTCOMPENSATE               //插入拆分
#define ID_TEXT_TIMEVALUE                      //时间值
#define ID_TEXT_MUSICSETUP                     //音乐设置
#define ID_TEXT_SELECTMUSICFILE                //选择音乐文件
#define ID_TEXT_MUSICTIME                      //音乐时间
#define ID_TEXT_AVGBPM                         //平均节拍
#define ID_TEXT_BEATTIME                       //每拍时间
#define ID_TEXT_TIMESCALE                      //时间刻度
#define ID_TEXT_TIMESCALE_DESC                 //时间刻度描述
#define ID_TEXT_ADDLAYER                       //添加层
#define ID_TEXT_SELECTLANGUAGE                 //选择语言
#define ID_TEXT_LANGUAGE                       //语言
#define ID_TEXT_ADDMUSIC                       //添加音乐
#define ID_TEXT_MODGROUPNAME                   //修改组名
#define ID_TEXT_COPY                           //复制
#define ID_TEXT_PASTE                          //粘贴
#define ID_TEXT_CUT                            //剪切
#define ID_TEXT_SINGLESIMU                     //单块仿真
#define ID_TEXT_CANCELSIMU                     //取消仿真
#define ID_TEXT_INSERTGROUP                    //插入组
#define ID_TEXT_SAVETOCMD                      //保存到指令盒
#define ID_TEXT_MODGROUPINFO                   //修改组信息
#define ID_TEXT_INSERTCOPYITEM                 //插入复制项
#define ID_TEXT_ADDCOPYITEM                    //添加复制项
#define ID_TEXT_DELETEROW                      //删除行
#define ID_TEXT_INSERTACTION                   //插入动作
#define ID_TEXT_SETBEGIN                       //设为开始点
#define ID_TEXT_SETEND                         //设为结束点
#define ID_TEXT_SELECTALLMUSIC                 //选择整首音乐
#define ID_TEXT_GOTO                           //转到
#define ID_TEXT_ANGOLA                         //安哥拉
#define ID_TEXT_AFGHANISTAN                    //阿富汗
#define ID_TEXT_ALBANIA                        //阿尔巴尼亚
#define ID_TEXT_ALGERIA                        //阿尔及利亚
#define ID_TEXT_ANDORRA                        //安道尔共和国
#define ID_TEXT_ANGUILLA                       //安圭拉岛
#define ID_TEXT_ANTIGUAANDBARBUDA              //安提瓜和巴布达
#define ID_TEXT_ARGENTINA                      //阿根廷
#define ID_TEXT_ARMENIA                        //亚美尼亚
#define ID_TEXT_ASCENSION                      //阿森松
#define ID_TEXT_AUSTRALIA                      //澳大利亚
#define ID_TEXT_AUSTRIA                        //奥地利
#define ID_TEXT_AZERBAIJAN                     //阿塞拜疆
#define ID_TEXT_BAHAMAS                        //巴哈马
#define ID_TEXT_BAHRAIN                        //巴林
#define ID_TEXT_BANGLADESH                     //孟加拉国
#define ID_TEXT_BARBADOS                       //巴巴多斯
#define ID_TEXT_BELARUS                        //白俄罗斯
#define ID_TEXT_BELGIUM                        //比利时
#define ID_TEXT_BELIZE                         //伯利兹
#define ID_TEXT_BENIN                          //贝宁
#define ID_TEXT_BERMUDAIS                      //百慕大群岛
#define ID_TEXT_BOLIVIA                        //玻利维亚
#define ID_TEXT_BOTSWANA                       //博茨瓦纳
#define ID_TEXT_BRAZIL                         //巴西
#define ID_TEXT_BRUNEI                         //文莱
#define ID_TEXT_BULGARIA                       //保加利亚
#define ID_TEXT_BURKINAFASO                    //布基纳法索
#define ID_TEXT_BURMA                          //缅甸
#define ID_TEXT_BURUNDI                        //布隆迪
#define ID_TEXT_CAMEROON                       //喀麦隆
#define ID_TEXT_CANADA                         //加拿大
#define ID_TEXT_CAYMANIS                       //开曼群岛
#define ID_TEXT_CENTIALAFRICANREPUBLIC         //中非共和国
#define ID_TEXT_CHAD                           //乍得
#define ID_TEXT_CHILE                          //智利
#define ID_TEXT_CHINA                          //中国
#define ID_TEXT_COLOMBIA                       //哥伦比亚
#define ID_TEXT_CONGO                          //刚果
#define ID_TEXT_COOKIS                         //库克群岛
#define ID_TEXT_COSTARICA                      //哥斯达黎加
#define ID_TEXT_CUBA                           //古巴
#define ID_TEXT_CYPRUS                         //塞浦路斯
#define ID_TEXT_CZECHREPUBLIC                  //捷克
#define ID_TEXT_DENMARK                        //丹麦
#define ID_TEXT_DJIBOUTI                       //吉布提
#define ID_TEXT_DOMINICAREP                    //多米尼加共和国
#define ID_TEXT_ECUADOR                        //厄瓜多尔
#define ID_TEXT_EGYPT                          //埃及
#define ID_TEXT_EISALVADOR                     //萨尔瓦多
#define ID_TEXT_ESTONIA                        //爱沙尼亚
#define ID_TEXT_ETHIOPIA                       //埃塞俄比亚
#define ID_TEXT_FIJI                           //斐济
#define ID_TEXT_FINLAND                        //芬兰
#define ID_TEXT_FRANCE                         //法国
#define ID_TEXT_FRENCHGUIANA                   //法属圭亚那
#define ID_TEXT_GABON                          //加蓬
#define ID_TEXT_GAMBIA                         //冈比亚
#define ID_TEXT_GEORGIA                        //格鲁吉亚
#define ID_TEXT_GERMANY                        //德国
#define ID_TEXT_GHANA                          //加纳
#define ID_TEXT_GIBRALTAR                      //直布罗陀
#define ID_TEXT_GREECE                         //希腊
#define ID_TEXT_GRENADA                        //格林纳达
#define ID_TEXT_GUAM                           //关岛
#define ID_TEXT_GUATEMALA                      //危地马拉
#define ID_TEXT_GUINEA                         //几内亚
#define ID_TEXT_GUYANA                         //圭亚那
#define ID_TEXT_HAITI                          //海地
#define ID_TEXT_HONDURAS                       //洪都拉斯
#define ID_TEXT_HONGKONG                       //香港
#define ID_TEXT_HUNGARY                        //匈牙利
#define ID_TEXT_ICELAND                        //冰岛
#define ID_TEXT_INDIA                          //印度
#define ID_TEXT_INDONESIA                      //印度尼西亚
#define ID_TEXT_IRAN                           //伊朗
#define ID_TEXT_IRAQ                           //伊拉克
#define ID_TEXT_IRELAND                        //爱尔兰
#define ID_TEXT_ISRAEL                         //以色列
#define ID_TEXT_ITALY                          //意大利
#define ID_TEXT_IVORYCOAST                     //科特迪瓦
#define ID_TEXT_JAMAICA                        //牙买加
#define ID_TEXT_JAPAN                          //日本
#define ID_TEXT_JORDAN                         //约旦
#define ID_TEXT_KAMPUCHEA                      //柬埔寨
#define ID_TEXT_KAZAKSTAN                      //哈萨克斯坦
#define ID_TEXT_KENYA                          //肯尼亚
#define ID_TEXT_KOREA                          //韩国
#define ID_TEXT_KUWAIT                         //科威特
#define ID_TEXT_KYRGYZSTAN                     //吉尔吉斯坦
#define ID_TEXT_LAOS                           //老挝
#define ID_TEXT_LATVIA                         //拉脱维亚
#define ID_TEXT_LEBANON                        //黎巴嫩
#define ID_TEXT_LESOTHO                        //莱索托
#define ID_TEXT_LIBERIA                        //利比里亚
#define ID_TEXT_LIBYA                          //利比亚
#define ID_TEXT_LIECHTENSTEIN                  //列支敦士登
#define ID_TEXT_LITHUANIA                      //立陶宛
#define ID_TEXT_LUXEMBOURG                     //卢森堡
#define ID_TEXT_MACAO                          //澳门
#define ID_TEXT_MADAGASCAR                     //马达加斯加
#define ID_TEXT_MALAWI                         //马拉维
#define ID_TEXT_MALAYSIA                       //马来西亚
#define ID_TEXT_MALDIVES                       //马尔代夫
#define ID_TEXT_MALI                           //马里
#define ID_TEXT_MALTA                          //马耳他
#define ID_TEXT_MARIANAIS                      //马里亚那群岛
#define ID_TEXT_MARTINIQUE                     //马提尼克
#define ID_TEXT_MAURITIUS                      //毛里求斯
#define ID_TEXT_MEXICO                         //墨西哥
#define ID_TEXT_MOLDOVA                        //摩尔多瓦
#define ID_TEXT_MONACO                         //摩纳哥
#define ID_TEXT_MONGOLIA                       //蒙古
#define ID_TEXT_MONTSERRATIS                   //蒙特塞拉特岛
#define ID_TEXT_MOROCCO                        //摩洛哥
#define ID_TEXT_MOZAMBIQUE                     //莫桑比克
#define ID_TEXT_NAMIBIA                        //纳米比亚
#define ID_TEXT_NAURU                          //瑙鲁
#define ID_TEXT_NEPAL                          //尼泊尔
#define ID_TEXT_NETHERIANDSANTILLES            //荷属安的列斯
#define ID_TEXT_NETHERLANDS                    //荷兰
#define ID_TEXT_NEWZEALAND                     //新西兰
#define ID_TEXT_NICARAGUA                      //尼加拉瓜
#define ID_TEXT_NIGER                          //尼日尔
#define ID_TEXT_NIGERIA                        //尼日利亚
#define ID_TEXT_NORTHKOREA                     //朝鲜
#define ID_TEXT_NORWAY                         //挪威
#define ID_TEXT_OMAN                           //阿曼
#define ID_TEXT_PAKISTAN                       //巴基斯坦
#define ID_TEXT_PANAMA                         //巴拿马
#define ID_TEXT_PAPUANEWCUINEA                 //巴布亚新几内亚
#define ID_TEXT_PARAGUAY                       //巴拉圭
#define ID_TEXT_PERU                           //秘鲁
#define ID_TEXT_PHILIPPINES                    //菲律宾
#define ID_TEXT_POLAND                         //波兰
#define ID_TEXT_FRENCHPOLYNESIA                //法属玻利尼西亚
#define ID_TEXT_PORTUGAL                       //葡萄牙
#define ID_TEXT_PUERTORICO                     //波多黎各
#define ID_TEXT_QATAR                          //卡塔尔
#define ID_TEXT_REUNION                        //留尼旺
#define ID_TEXT_ROMANIA                        //罗马尼亚
#define ID_TEXT_RUSSIA                         //俄罗斯
#define ID_TEXT_SAINTLUEIA                     //圣卢西亚
#define ID_TEXT_SAINTVINCENT                   //圣文森特岛
#define ID_TEXT_SAMOAEASTERN                   //东萨摩亚(美)
#define ID_TEXT_SAMOAWESTERN                   //西萨摩亚
#define ID_TEXT_SANMARINO                      //圣马力诺
#define ID_TEXT_SAOTOMEANDPRINCIPE             //圣多美和普林西比
#define ID_TEXT_SAUDIARABIA                    //沙特阿拉伯
#define ID_TEXT_SENEGAL                        //塞内加尔
#define ID_TEXT_SEYCHELLES                     //塞舌尔
#define ID_TEXT_SIERRALEONE                    //塞拉利昂
#define ID_TEXT_SINGAPORE                      //新加坡
#define ID_TEXT_SLOVAKIA                       //斯洛伐克
#define ID_TEXT_SLOVENIA                       //斯洛文尼亚
#define ID_TEXT_SOLOMONIS                      //所罗门群岛
#define ID_TEXT_SOMALI                         //索马里
#define ID_TEXT_SOUTHAFRICA                    //南非
#define ID_TEXT_SPAIN                          //西班牙
#define ID_TEXT_SRILANKA                       //斯里兰卡
#define ID_TEXT_STLUCIA                        //圣卢西亚
#define ID_TEXT_STVINCENT                      //圣文森特
#define ID_TEXT_SUDAN                          //苏丹
#define ID_TEXT_SURINAME                       //苏里南
#define ID_TEXT_SWAZILAND                      //斯威士兰
#define ID_TEXT_SWEDEN                         //瑞典
#define ID_TEXT_SWITZERLAND                    //瑞士
#define ID_TEXT_SYRIA                          //叙利亚
#define ID_TEXT_TAIWAN                         //台湾省
#define ID_TEXT_TAJIKSTAN                      //塔吉克斯坦
#define ID_TEXT_TANZANIA                       //坦桑尼亚
#define ID_TEXT_THAILAND                       //泰国
#define ID_TEXT_TOGO                           //多哥
#define ID_TEXT_TONGA                          //汤加
#define ID_TEXT_TRINIDADANDTOBAGO              //特立尼达和多巴哥
#define ID_TEXT_TUNISIA                        //突尼斯
#define ID_TEXT_TURKEY                         //土耳其
#define ID_TEXT_TURKMENISTAN                   //土库曼斯坦
#define ID_TEXT_UGANDA                         //乌干达
#define ID_TEXT_UKRAINE                        //乌克兰
#define ID_TEXT_UNITEDARABEMIRATES             //阿拉伯联合酋长国
#define ID_TEXT_UNITEDKIONGDOM                 //英国
#define ID_TEXT_UNITEDSTATESOFAMERICA          //美国
#define ID_TEXT_URUGUAY                        //乌拉圭
#define ID_TEXT_UZBEKISTAN                     //乌兹别克斯坦
#define ID_TEXT_VENEZUELA                      //委内瑞拉
#define ID_TEXT_VIETNAM                        //越南
#define ID_TEXT_YEMEN                          //也门
#define ID_TEXT_YUGOSLAVIA                     //南斯拉夫
#define ID_TEXT_ZIMBABWE                       //津巴布韦
#define ID_TEXT_ZAIRE                          //扎伊尔
#define ID_TEXT_ZAMBIA                         //赞比亚